import React,{Component} from "react";
import {StyleSheet} from "react-native";

const styles = StyleSheet.create({
    container:{
      backgroundColor:'#1b1d1b'
    },
    divide:{
        width:'100%',
        height:10
    },
    btnBox:{
        marginLeft:40,
        marginRight:40
    },
    btnYellow:{
        height:44,
        backgroundColor:'#0B102A',
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        width:'100%'
    },
    btnYellowText:{
        fontSize:18,
        color:'#fff',
        fontWeight:'bold'
    },
    formTitle:{
        backgroundColor:'#fff',
        height:40,
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        width:'100%',
        borderBottomWidth:1,
        borderBottomColor:'#F5F5F5',
        paddingLeft:15,
        paddingRight:15
    },
    formGroup:{
        backgroundColor:'#fff',
        height:40,
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        width:'100%',
        borderBottomWidth:1,
        borderBottomColor:'#F5F5F5',
        paddingLeft:15,
        paddingRight:15
    },    
    formLabel:{
        color:'#0B102A',
        fontSize:16,
        marginRight:10
    },
    formControl:{
        height:40,
        flex:1,
        fontSize:14,
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
    },
    formGroupLg:{
        backgroundColor:'#fff',
        width:'100%',
        borderBottomWidth:1,
        borderBottomColor:'#F5F5F5',
        paddingLeft:15,
        paddingRight:15
    },
    formLabelLg:{
        paddingTop:10,
        paddingBottom:10,
        borderBottomWidth:1,
        borderBottomColor:'#F5F5F5',
        width:'100%',
    },
    formControlLg:{
        height:80,
        fontSize:24,
        width:'100%',
    },
    formTip:{
        paddingTop:15,
        paddingRight:15,
        paddingBottom:15,
        paddingLeft:15,
        display:'flex',
        flexDirection:'row',
        alignItems:'center'
    }
})

module.exports = {
    GlobalStyle:styles
}